"""Setup and Foundation Verification Tests.

Validates:
1. Core imports and environment (including sentence-transformers)
2. Centralized configuration loading and defaults
3. Data model instantiation and type consistency
4. Pipeline lifecycle, extension interfaces, and basic query processing
"""

import pytest
from src.config import AppConfig, config
from src.models import (
    CacheEntry,
    DecisionResult,
    EvaluationMetrics,
    LLMResponse,
    PipelineResponse,
    QueryRequest,
)
from src.pipeline import (
    CacheInterface,
    DecisionInterface,
    DefaultPreprocessor,
    EvaluatorInterface,
    LLMInterface,
    MockCache,
    MockDecisionEngine,
    MockEvaluator,
    MockLLM,
    QueryPreprocessorInterface,
    SemanticCachingPipeline,
)


def test_sentence_transformers_import():
    """Verify sentence_transformers can be imported in the environment."""
    from sentence_transformers import SentenceTransformer

    assert SentenceTransformer is not None


def test_config_loading():
    """Test configuration dataclass and default parameters."""
    cfg = AppConfig()
    assert cfg.project_name == "Semantic Caching for LLM - Cost-Benefit Cascade Flow"
    assert cfg.similarity_threshold == 0.85
    assert cfg.embedding_model_name == "all-MiniLM-L6-v2"
    assert cfg.cache_dir.exists()


def test_data_models_instantiation():
    """Test creating instances of all core data models."""
    req = QueryRequest(query="test query", session_id="sess_123")
    assert req.query == "test query"
    assert req.session_id == "sess_123"

    entry = CacheEntry(query="test query", response="cached answer", similarity_score=0.95)
    assert entry.response == "cached answer"
    assert entry.similarity_score == 0.95

    dec = DecisionResult(route="CACHE_HIT", estimated_cost=0.0, confidence=0.95)
    assert dec.route == "CACHE_HIT"

    llm_resp = LLMResponse(text="llm answer", model_name="mock-llm-v1", tokens_used=10)
    assert llm_resp.text == "llm answer"

    pipe_resp = PipelineResponse(
        query="test",
        response_text="answer",
        source="cache",
        similarity_score=0.95,
        decision=dec,
        latency_ms=1.5,
    )
    assert pipe_resp.source == "cache"
    assert pipe_resp.latency_ms == 1.5

    metrics = EvaluationMetrics(total_queries=1, cache_hits=1, hit_rate=1.0)
    assert metrics.hit_rate == 1.0


def test_interface_compliance():
    """Verify mock classes inherit from defined abstract interfaces."""
    assert issubclass(DefaultPreprocessor, QueryPreprocessorInterface)
    assert issubclass(MockCache, CacheInterface)
    assert issubclass(MockDecisionEngine, DecisionInterface)
    assert issubclass(MockLLM, LLMInterface)
    assert issubclass(MockEvaluator, EvaluatorInterface)


def test_pipeline_basic_query_flow():
    """Test pipeline processes query, caches on miss, and hits on repeat."""
    pipeline = SemanticCachingPipeline()

    # Query 1: Initial query -> Cache Miss -> Generated by LLM -> Stored in Cache
    resp1 = pipeline.process_query("What is machine learning?")
    assert resp1.source == "llm"
    assert resp1.decision.route == "DIRECT_LLM"
    assert "Machine learning" in resp1.response_text
    assert pipeline.cache.size() == 1

    # Query 2: Repeated query -> Cache Hit
    resp2 = pipeline.process_query("What is machine learning?")
    assert resp2.source == "cache"
    assert resp2.decision.route == "CACHE_HIT"
    assert resp2.response_text == resp1.response_text

    # Verify metrics accumulated
    metrics = pipeline.evaluator.get_metrics()
    assert metrics.total_queries == 2
    assert metrics.cache_hits == 1
    assert metrics.cache_misses == 1
    assert metrics.hit_rate == 0.5
