"""Data models for Semantic Caching for LLM.

Defines typed dataclasses for requests, cache entries, cascade decisions,
LLM responses, pipeline outputs, and evaluation metrics.
"""

from dataclasses import dataclass, field
import time
from typing import Any, Dict, List, Optional


@dataclass
class QueryRequest:
    """Incoming query representation."""

    query: str
    session_id: Optional[str] = None
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CacheEntry:
    """Represents a cached query-response pair and optional embedding vector."""

    query: str
    response: str
    embedding: Optional[List[float]] = None
    similarity_score: float = 0.0
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DecisionResult:
    """Represents the routing and cost-benefit outcome from the cascade engine."""

    route: str  # e.g., "CACHE_HIT", "DIRECT_LLM", "CASCADE_LIGHT", "CASCADE_HEAVY"
    estimated_cost: float = 0.0
    confidence: float = 0.0
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LLMResponse:
    """Represents a raw response generated by an LLM or fallback model."""

    text: str
    model_name: str
    tokens_used: int = 0
    latency_ms: float = 0.0
    cost: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PipelineResponse:
    """Final unified response returned by the semantic caching pipeline."""

    query: str
    response_text: str
    source: str  # "cache" or "llm"
    similarity_score: Optional[float] = None
    decision: Optional[DecisionResult] = None
    latency_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class EvaluationMetrics:
    """Metrics recorded for evaluation and performance analysis."""

    total_queries: int = 0
    cache_hits: int = 0
    cache_misses: int = 0
    hit_rate: float = 0.0
    total_cost_saved: float = 0.0
    avg_latency_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)
