"""Shared data models for the semantic caching pipeline."""

from dataclasses import dataclass, field
import time
from typing import Any, Dict, List, Optional


@dataclass
class QueryRequest:
    """Incoming user query."""

    query: str
    session_id: Optional[str] = None
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CacheEntry:
    """Cached query-response pair.

    The embedding is optional because the pipeline does not require
    knowledge of how the cache represents queries internally.
    """

    query: str
    response: str
    embedding: Optional[List[float]] = None
    similarity_score: float = 0.0
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DecisionResult:
    """Execution decision metadata for a pipeline response.

    This is intentionally generic. It is not tied to a separate
    cascade implementation.
    """

    route: str
    estimated_cost: float = 0.0
    confidence: float = 0.0
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LLMResponse:
    """Raw response generated by an LLM provider."""

    text: str
    model_name: str
    tokens_used: int = 0
    latency_ms: float = 0.0
    cost: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PipelineResponse:
    """Final response returned by the pipeline."""

    query: str
    response_text: str
    source: str
    similarity_score: Optional[float] = None
    decision: Optional[DecisionResult] = None
    latency_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class EvaluationMetrics:
    """Metrics produced by the evaluation component."""

    total_queries: int = 0
    cache_hits: int = 0
    cache_misses: int = 0
    hit_rate: float = 0.0
    total_cost_saved: float = 0.0
    avg_latency_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)
